In [3]:
# sgenerate a set of exam scores with population mean 80 and standard deviation 5

import random
import numpy as np
import matplotlib.pyplot as plt

def generate_scores(n):
    scores = []
    for i in range(n):
        scores.append(random.gauss(80,5))
    return scores

# generate conversion scores for a web site with and without a new feature

def generate_conversion_scores_with_feature(n):
    scores = []
    for i in range(n):
        scores.append(random.gauss(0.1,0.01))
    return scores

def generate_conversion_scores_without_feature(n):
    scores = []
    for i in range(n):
        scores.append(random.gauss(0.08,0.01))
    return scores

# generate a data set with blood pressure levels before and after a treatment

def generate_blood_pressure_before(n):
    scores = []
    for i in range(n):
        scores.append(random.gauss(120,10))
    return scores

def generate_blood_pressure_after(n):
    scores = []
    for i in range(n):
        scores.append(random.gauss(100,10))
    return scores

# generate contingency table of product preferences across age groups

def generate_product_preferences(n):
    table = np.zeros((3,3))
    for i in range(n):
        age = random.randint(0,2)
        product = random.randint(0,2)
        table[age,product] += 1
    return table


[[126. 105. 113.]
 [106. 116.  86.]
 [121. 110. 117.]]
